/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ReflectionsRouteImport } from './routes/reflections'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as LaborHistoryRouteImport } from './routes/labor-history'
import { Route as InformalityContextRouteImport } from './routes/informality-context'
import { Route as DiscussionRouteImport } from './routes/discussion'
import { Route as ClimateShocksRouteImport } from './routes/climate-shocks'
import { Route as BackgroundRouteImport } from './routes/background'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionsRoute = ReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const LaborHistoryRoute = LaborHistoryRouteImport.update({
  id: '/labor-history',
  path: '/labor-history',
  getParentRoute: () => rootRouteImport,
} as any)
const InformalityContextRoute = InformalityContextRouteImport.update({
  id: '/informality-context',
  path: '/informality-context',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimateShocksRoute = ClimateShocksRouteImport.update({
  id: '/climate-shocks',
  path: '/climate-shocks',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundRoute = BackgroundRouteImport.update({
  id: '/background',
  path: '/background',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/climate-shocks': typeof ClimateShocksRoute
  '/discussion': typeof DiscussionRoute
  '/informality-context': typeof InformalityContextRoute
  '/labor-history': typeof LaborHistoryRoute
  '/methodology': typeof MethodologyRoute
  '/references': typeof ReferencesRoute
  '/reflections': typeof ReflectionsRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/climate-shocks': typeof ClimateShocksRoute
  '/discussion': typeof DiscussionRoute
  '/informality-context': typeof InformalityContextRoute
  '/labor-history': typeof LaborHistoryRoute
  '/methodology': typeof MethodologyRoute
  '/references': typeof ReferencesRoute
  '/reflections': typeof ReflectionsRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/background': typeof BackgroundRoute
  '/climate-shocks': typeof ClimateShocksRoute
  '/discussion': typeof DiscussionRoute
  '/informality-context': typeof InformalityContextRoute
  '/labor-history': typeof LaborHistoryRoute
  '/methodology': typeof MethodologyRoute
  '/references': typeof ReferencesRoute
  '/reflections': typeof ReflectionsRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/background'
    | '/climate-shocks'
    | '/discussion'
    | '/informality-context'
    | '/labor-history'
    | '/methodology'
    | '/references'
    | '/reflections'
    | '/results'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/background'
    | '/climate-shocks'
    | '/discussion'
    | '/informality-context'
    | '/labor-history'
    | '/methodology'
    | '/references'
    | '/reflections'
    | '/results'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/background'
    | '/climate-shocks'
    | '/discussion'
    | '/informality-context'
    | '/labor-history'
    | '/methodology'
    | '/references'
    | '/reflections'
    | '/results'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackgroundRoute: typeof BackgroundRoute
  ClimateShocksRoute: typeof ClimateShocksRoute
  DiscussionRoute: typeof DiscussionRoute
  InformalityContextRoute: typeof InformalityContextRoute
  LaborHistoryRoute: typeof LaborHistoryRoute
  MethodologyRoute: typeof MethodologyRoute
  ReferencesRoute: typeof ReferencesRoute
  ReflectionsRoute: typeof ReflectionsRoute
  ResultsRoute: typeof ResultsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflections': {
      id: '/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof ReflectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labor-history': {
      id: '/labor-history'
      path: '/labor-history'
      fullPath: '/labor-history'
      preLoaderRoute: typeof LaborHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informality-context': {
      id: '/informality-context'
      path: '/informality-context'
      fullPath: '/informality-context'
      preLoaderRoute: typeof InformalityContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion': {
      id: '/discussion'
      path: '/discussion'
      fullPath: '/discussion'
      preLoaderRoute: typeof DiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/climate-shocks': {
      id: '/climate-shocks'
      path: '/climate-shocks'
      fullPath: '/climate-shocks'
      preLoaderRoute: typeof ClimateShocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background': {
      id: '/background'
      path: '/background'
      fullPath: '/background'
      preLoaderRoute: typeof BackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackgroundRoute: BackgroundRoute,
  ClimateShocksRoute: ClimateShocksRoute,
  DiscussionRoute: DiscussionRoute,
  InformalityContextRoute: InformalityContextRoute,
  LaborHistoryRoute: LaborHistoryRoute,
  MethodologyRoute: MethodologyRoute,
  ReferencesRoute: ReferencesRoute,
  ReflectionsRoute: ReflectionsRoute,
  ResultsRoute: ResultsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
